### ISSUE TITLE
candle open/close values do not match provider ui values

### ISSUE THREAD

**Issue by craveica** [VitalySvyatyuk/pocket_option_trading_bot#12]
only tested po_bot_indicators and the values for candle open/close are completely different from what pocketoption tool tips say.

**Comment by VitalySvyatyuk** [comment]
No, you're mistaken. You can test candles by plotting them.

**Comment by craveica** [comment]
I just print quotes[-1].open and quotes[-1].close and mouse over that specific candle and the values many times are offset quite a bit,

**Comment by craveica** [comment]
the issue is that the messages from websocket can be timestamp.001 and timestamp.999 for example. If you take only timestamp.001 you will miss some data, that makes difference on 1 min TF. For larger TFs will count less.

**Comment by VitalySvyatyuk** [comment]
Thanks for the information. It is not a big deal though

**Comment by craveica** [comment]
Feeding the indicators with wrong data, may yield in fake or missing signals. Anyways, since the fix is trivial, I will close this issue.
