### ISSUE TITLE
Can it process for less than 1min timeframe

### ISSUE THREAD

**Issue by cibogga** [VitalySvyatyuk/pocket_option_trading_bot#2]
Hi. Great script. Please how do i make po_bot_ml.py process for less than 1min timeframe. It crashes whenever i change the time frame to any below 1min

**Comment by VitalySvyatyuk** [comment]
Hi @cibogga . You can't use < 1 min for `po_bot_ml` and `po_bot_indicators`. It is how the data received from PO websocket. If you need < 1 min, have a look at `po_bot`.

**Comment by x-ender** [comment]
Thanks

**Comment by VitalySvyatyuk** [comment]
non-OTC pairs available only from Monday to Friday. To change currency to non-OTC with payout > 75, update `po_bot.py`:
1. change line 252 from `if estimated_profit != '+92%':` to `if int(estimated_profit.replace('+', '').replace('%', '')) < 75:`
2. change line 119 from `currencies = driver.find_elements(By.XPATH, "//li[contains(., '92%')]")` to `currencies = driver.find_elements(By.XPATH, "//li[contains(., '%')]")`
3. change line 123 from `currency = random.choice(currencies)` to `currency = random.choice(currencies[:15])`
4. change line 124 from `if CURRENCY not in currency.text:` to `if CURRENCY not in currency.text and 'OTC' not in currency.text:`
