### ISSUE TITLE
No file there stock_indicators

### ISSUE THREAD

**Issue by azeemamjad** [VitalySvyatyuk/pocket_option_trading_bot#3]
Hi! I wanted to use this in my project but there is an error related to these two lines in po_bot_indicator.py

from stock_indicators import indicators
from stock_indicators.indicators.common.quote import Quote

these files are not present there 

can you give me an idea for solving this problem 

Thanks
![image](https://github.com/VitalySvyatyuk/pocket_option_trading_bot/assets/107496010/78cd4d71-9e46-41e1-aa39-f55f3b828b71)

**Comment by VitalySvyatyuk** [comment]
hi Azeem,
you have to install stock_indicators package: pip install stock_indicators. And don't forget to install .Net6

**Comment by azeemamjad** [comment]
Okay thanks buddy 🙂
